/**
 * Deletes `android/` and `ios/` before a cloud build.
 *
 * This is a Continuous Native Generation project: both folders are gitignored and regenerated by
 * `expo prebuild --clean` on every build, in the cloud as much as locally. Nothing in them is an
 * input to anything — but a local Gradle run leaves 1.6 GB of `.cxx` staging, object files and
 * NDK output behind, and it grows every time you build.
 *
 * That would be merely untidy if it stayed on disk. It does not: the EAS CLI walks the tree and
 * uploads what it finds, and this folder was going up with every single build. It took the
 * project archive from 20 MB to a gigabyte, and — because the folder accumulates — the number
 * climbed with each release. `.easignore` names `android/` and `ios/` and is evidently not being
 * honoured; rather than keep guessing at which root the CLI walks from and which ignore file it
 * reads, the files simply are not there when it looks.
 *
 * The cost is a slower *local* Gradle build afterwards, which re-downloads the NDK. Cloud builds
 * pay nothing, because they were always going to prebuild from scratch anyway.
 */
import { existsSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const app = join(dirname(fileURLToPath(import.meta.url)), '..');

for (const name of ['android', 'ios']) {
  const at = join(app, name);
  if (!existsSync(at)) continue;
  // `force` because a file held open by an editor is not a reason to fail a release, and the
  // next `prebuild --clean` will take whatever is left.
  rmSync(at, { recursive: true, force: true });
  console.log(`cleaned ${name}/`);
}
