/* eslint-disable */
// GENERATED by scripts/build-faces.mjs — do not edit. Run `node scripts/build-faces.mjs`.
//
// `cx`/`cy` are the part's centre in portrait design space, measured from its real rendered
// bounding box, so the renderer can place every layer with a single `setPosition` and no
// per-part fudging. `tint` names the colour slot the run multiplies the part by.

export type FaceTintSlot = 'none' | 'skin' | 'skinShadow' | 'skinLight' | 'hair' | 'robe' | 'robeDark' | 'robeLight';

export interface FacePartDef {
  key: string;
  /** Paint order, low to high. */
  layer: number;
  tint: FaceTintSlot;
  cx: number;
  cy: number;
  w: number;
  h: number;
}

export const FACE_PART_DEFS: readonly FacePartDef[] = [
  {
    "key": "plate-common",
    "layer": 10,
    "tint": "none",
    "cx": 0,
    "cy": -1,
    "w": 136,
    "h": 170
  },
  {
    "key": "plate-rare",
    "layer": 10,
    "tint": "none",
    "cx": 0,
    "cy": -1,
    "w": 136,
    "h": 170
  },
  {
    "key": "plate-epic",
    "layer": 10,
    "tint": "none",
    "cx": 0,
    "cy": -1,
    "w": 136,
    "h": 170
  },
  {
    "key": "plate-legendary",
    "layer": 10,
    "tint": "none",
    "cx": 0,
    "cy": -1,
    "w": 136,
    "h": 170
  },
  {
    "key": "robe-body",
    "layer": 20,
    "tint": "robe",
    "cx": 0,
    "cy": 66,
    "w": 96,
    "h": 58
  },
  {
    "key": "robe-armour",
    "layer": 20,
    "tint": "robe",
    "cx": 0,
    "cy": 66,
    "w": 96,
    "h": 58
  },
  {
    "key": "robe-sheen",
    "layer": 22,
    "tint": "robeLight",
    "cx": 26,
    "cy": 66,
    "w": 44,
    "h": 58
  },
  {
    "key": "neck",
    "layer": 25,
    "tint": "skinShadow",
    "cx": 0,
    "cy": 36,
    "w": 22,
    "h": 26
  },
  {
    "key": "head-oval",
    "layer": 30,
    "tint": "skin",
    "cx": 0,
    "cy": -12,
    "w": 62,
    "h": 82
  },
  {
    "key": "head-narrow",
    "layer": 30,
    "tint": "skin",
    "cx": 0,
    "cy": -12,
    "w": 58,
    "h": 86
  },
  {
    "key": "head-broad",
    "layer": 30,
    "tint": "skin",
    "cx": -0.5,
    "cy": -12.5,
    "w": 69,
    "h": 79
  },
  {
    "key": "head-square",
    "layer": 30,
    "tint": "skin",
    "cx": -0.5,
    "cy": -12,
    "w": 65,
    "h": 82
  },
  {
    "key": "head-soft",
    "layer": 30,
    "tint": "skin",
    "cx": 0,
    "cy": -12,
    "w": 60,
    "h": 80
  },
  {
    "key": "ears",
    "layer": 28,
    "tint": "skinShadow",
    "cx": -0.5,
    "cy": -10,
    "w": 75,
    "h": 26
  },
  {
    "key": "collar-giaolinh",
    "layer": 35,
    "tint": "robeDark",
    "cx": -16,
    "cy": 55,
    "w": 40,
    "h": 48
  },
  {
    "key": "collar-giaolinh-over",
    "layer": 36,
    "tint": "robeLight",
    "cx": 16,
    "cy": 55,
    "w": 40,
    "h": 48
  },
  {
    "key": "collar-twoflap",
    "layer": 35,
    "tint": "robeDark",
    "cx": -17,
    "cy": 58,
    "w": 38,
    "h": 42
  },
  {
    "key": "collar-twoflap-over",
    "layer": 36,
    "tint": "robeLight",
    "cx": 17,
    "cy": 58,
    "w": 38,
    "h": 42
  },
  {
    "key": "sash-ochre",
    "layer": 37,
    "tint": "none",
    "cx": 0,
    "cy": 69.5,
    "w": 52,
    "h": 9
  },
  {
    "key": "sash-baldric",
    "layer": 37,
    "tint": "none",
    "cx": 0,
    "cy": 65,
    "w": 72,
    "h": 16
  },
  {
    "key": "collar-nguthan",
    "layer": 35,
    "tint": "robeLight",
    "cx": 0,
    "cy": 36,
    "w": 36,
    "h": 14
  },
  {
    "key": "collar-nguthan-body",
    "layer": 36,
    "tint": "robe",
    "cx": 2,
    "cy": 58,
    "w": 48,
    "h": 42
  },
  {
    "key": "buttons-five",
    "layer": 37,
    "tint": "none",
    "cx": 19,
    "cy": 59,
    "w": 8,
    "h": 36
  },
  {
    "key": "collar-yem-wrap",
    "layer": 35,
    "tint": "robeLight",
    "cx": 0,
    "cy": 47.5,
    "w": 56,
    "h": 29
  },
  {
    "key": "yem",
    "layer": 36,
    "tint": "none",
    "cx": 0,
    "cy": 54,
    "w": 44,
    "h": 34
  },
  {
    "key": "sash-waist",
    "layer": 37,
    "tint": "none",
    "cx": 0,
    "cy": 71.5,
    "w": 48,
    "h": 9
  },
  {
    "key": "collar-nhatbinh",
    "layer": 35,
    "tint": "robeDark",
    "cx": 0,
    "cy": 45,
    "w": 68,
    "h": 36
  },
  {
    "key": "collar-nhatbinh-trim",
    "layer": 36,
    "tint": "none",
    "cx": 0,
    "cy": 45,
    "w": 68,
    "h": 36
  },
  {
    "key": "kesa",
    "layer": 35,
    "tint": "none",
    "cx": 0,
    "cy": 60,
    "w": 72,
    "h": 42
  },
  {
    "key": "hair-crown",
    "layer": 40,
    "tint": "hair",
    "cx": -0.5,
    "cy": -39.5,
    "w": 65,
    "h": 25
  },
  {
    "key": "hair-cropped",
    "layer": 40,
    "tint": "hair",
    "cx": -0.5,
    "cy": -42,
    "w": 65,
    "h": 22
  },
  {
    "key": "hair-long",
    "layer": 40,
    "tint": "hair",
    "cx": 0,
    "cy": -9.5,
    "w": 70,
    "h": 81
  },
  {
    "key": "topknot",
    "layer": 41,
    "tint": "hair",
    "cx": 0,
    "cy": -57,
    "w": 24,
    "h": 20
  },
  {
    "key": "topknot-tall",
    "layer": 41,
    "tint": "hair",
    "cx": 0,
    "cy": -60,
    "w": 28,
    "h": 24
  },
  {
    "key": "bun-high",
    "layer": 41,
    "tint": "hair",
    "cx": 0,
    "cy": -59,
    "w": 34,
    "h": 24
  },
  {
    "key": "bun-low",
    "layer": 41,
    "tint": "hair",
    "cx": 0,
    "cy": -54,
    "w": 30,
    "h": 22
  },
  {
    "key": "hairpin",
    "layer": 42,
    "tint": "none",
    "cx": 0,
    "cy": -65,
    "w": 10,
    "h": 16
  },
  {
    "key": "hat-khanvan",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -46.5,
    "w": 68,
    "h": 27
  },
  {
    "key": "hat-khandong",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -47,
    "w": 70,
    "h": 24
  },
  {
    "key": "hat-phocdau-short",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -53,
    "w": 92,
    "h": 36
  },
  {
    "key": "hat-phocdau-long",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -53,
    "w": 110,
    "h": 36
  },
  {
    "key": "hat-phocdau-grand",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -53,
    "w": 126,
    "h": 36
  },
  {
    "key": "hat-helm",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -59,
    "w": 68,
    "h": 50
  },
  {
    "key": "hat-non",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -53.5,
    "w": 96,
    "h": 33
  },
  {
    "key": "hat-moqua",
    "layer": 50,
    "tint": "none",
    "cx": -0.5,
    "cy": -33,
    "w": 71,
    "h": 36
  },
  {
    "key": "hat-coronet",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -54,
    "w": 48,
    "h": 26
  },
  {
    "key": "hat-crown-nhatbinh",
    "layer": 50,
    "tint": "none",
    "cx": 0,
    "cy": -57,
    "w": 52,
    "h": 28
  },
  {
    "key": "hat-band",
    "layer": 50,
    "tint": "none",
    "cx": 1.5,
    "cy": -32,
    "w": 71,
    "h": 38
  },
  {
    "key": "scalp-shaven",
    "layer": 50,
    "tint": "skinLight",
    "cx": -0.5,
    "cy": -39.5,
    "w": 61,
    "h": 21
  },
  {
    "key": "scalp-dots",
    "layer": 51,
    "tint": "skinShadow",
    "cx": 0,
    "cy": -43,
    "w": 24,
    "h": 8
  },
  {
    "key": "brow-flat",
    "layer": 60,
    "tint": "hair",
    "cx": -0.5,
    "cy": -27,
    "w": 49,
    "h": 8
  },
  {
    "key": "brow-arched",
    "layer": 60,
    "tint": "hair",
    "cx": -0.5,
    "cy": -25.5,
    "w": 49,
    "h": 9
  },
  {
    "key": "brow-angled",
    "layer": 60,
    "tint": "hair",
    "cx": -0.5,
    "cy": -28.5,
    "w": 49,
    "h": 7
  },
  {
    "key": "eyes-almond",
    "layer": 62,
    "tint": "none",
    "cx": 0,
    "cy": -19.5,
    "w": 46,
    "h": 11
  },
  {
    "key": "eyes-wide",
    "layer": 62,
    "tint": "none",
    "cx": 0,
    "cy": -20,
    "w": 46,
    "h": 10
  },
  {
    "key": "eyes-narrow",
    "layer": 62,
    "tint": "none",
    "cx": 0,
    "cy": -19.5,
    "w": 46,
    "h": 11
  },
  {
    "key": "nose-straight",
    "layer": 64,
    "tint": "skinShadow",
    "cx": 0.5,
    "cy": -8,
    "w": 9,
    "h": 14
  },
  {
    "key": "nose-long",
    "layer": 64,
    "tint": "skinShadow",
    "cx": 1,
    "cy": -6.5,
    "w": 10,
    "h": 17
  },
  {
    "key": "nose-soft",
    "layer": 64,
    "tint": "skinShadow",
    "cx": 0.5,
    "cy": -9,
    "w": 9,
    "h": 12
  },
  {
    "key": "mouth-neutral",
    "layer": 66,
    "tint": "none",
    "cx": 0,
    "cy": 15.5,
    "w": 14,
    "h": 5
  },
  {
    "key": "mouth-smile",
    "layer": 66,
    "tint": "none",
    "cx": -0.5,
    "cy": 16,
    "w": 17,
    "h": 6
  },
  {
    "key": "mouth-firm",
    "layer": 66,
    "tint": "none",
    "cx": -0.5,
    "cy": 15.5,
    "w": 17,
    "h": 5
  },
  {
    "key": "mouth-lacquered",
    "layer": 66,
    "tint": "none",
    "cx": 0,
    "cy": 14.5,
    "w": 20,
    "h": 7
  },
  {
    "key": "beard-moustache",
    "layer": 70,
    "tint": "hair",
    "cx": 0,
    "cy": 10.5,
    "w": 26,
    "h": 9
  },
  {
    "key": "beard-goatee",
    "layer": 70,
    "tint": "hair",
    "cx": 0,
    "cy": 21.5,
    "w": 18,
    "h": 11
  },
  {
    "key": "beard-long",
    "layer": 70,
    "tint": "hair",
    "cx": 0,
    "cy": 20,
    "w": 26,
    "h": 28
  },
  {
    "key": "beard-full",
    "layer": 70,
    "tint": "hair",
    "cx": -0.5,
    "cy": 19.5,
    "w": 39,
    "h": 25
  },
  {
    "key": "mark-age",
    "layer": 72,
    "tint": "skinShadow",
    "cx": 0,
    "cy": -13.5,
    "w": 48,
    "h": 23
  },
  {
    "key": "mark-scar",
    "layer": 72,
    "tint": "skinShadow",
    "cx": -20.5,
    "cy": -22,
    "w": 7,
    "h": 20
  },
  {
    "key": "mark-tattoo",
    "layer": 73,
    "tint": "none",
    "cx": 7,
    "cy": 34,
    "w": 6,
    "h": 12
  },
  {
    "key": "mark-tattoo-court",
    "layer": 74,
    "tint": "none",
    "cx": -20.5,
    "cy": -21.5,
    "w": 9,
    "h": 9
  },
  {
    "key": "rank-rare",
    "layer": 80,
    "tint": "none",
    "cx": 52,
    "cy": 68,
    "w": 20,
    "h": 20
  },
  {
    "key": "rank-epic",
    "layer": 80,
    "tint": "none",
    "cx": 52,
    "cy": 68,
    "w": 20,
    "h": 20
  },
  {
    "key": "rank-legendary",
    "layer": 80,
    "tint": "none",
    "cx": 52,
    "cy": 68,
    "w": 20,
    "h": 20
  }
] as const;

/** Design-space bounds every part is authored against. */
export const FACE_VIEW = {"x":-68,"y":-88,"w":136,"h":174} as const;
