/**
 * Vendors the two open-licence typefaces the art direction calls for.
 *
 * Vietnamese kills most display faces: `ế ổ ữ ằ` stack two marks above the letter, and a face
 * without proper Vietnamese design either collides them or drops them. Be Vietnam Pro was drawn
 * for the language; Source Serif 4 carries a real Vietnamese subset. Both are SIL OFL.
 *
 * They are self-hosted rather than linked, because the game is offline-capable and a CDN font is a
 * silent fallback to Roboto waiting to happen — which is exactly the state this replaces.
 *
 * Only the latin, latin-ext and vietnamese subsets are kept; the rest is weight the game will never
 * render. Run with `node scripts/fetch-fonts.mjs`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'public/fonts';
const KEEP = new Set(['latin', 'latin-ext', 'vietnamese']);
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const CSS = 'https://fonts.googleapis.com/css2'
  + '?family=Be+Vietnam+Pro:wght@400;600;700'
  + '&family=Source+Serif+4:wght@600;700'
  + '&display=swap';

mkdirSync(OUT, { recursive: true });

const css = await (await fetch(CSS, { headers: { 'User-Agent': UA } })).text();

// Google's CSS is a run of `/* subset */ @font-face { … }` blocks; keep the ones we render.
const blocks = css.split('/*').slice(1).map((chunk) => `/*${chunk}`);
const kept = [];
const files = new Map();

for (const block of blocks) {
  const subset = block.match(/\/\*\s*([a-z-]+)\s*\*\//)?.[1];
  if (!subset || !KEEP.has(subset)) continue;

  const family = block.match(/font-family:\s*'([^']+)'/)?.[1] ?? 'font';
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) continue;

  const name = `${family.replace(/\s+/g, '')}-${weight}-${subset}.woff2`;
  files.set(name, url);
  // Relative, not `/fonts/${name}`: this stylesheet is served from inside /fonts/, and the game
  // is served from a repository sub-path on GitHub Pages, where a leading slash points at the
  // user site root. An absolute src there is a 404 on every face and a silent fall back to
  // whatever the phone had — which is the exact failure this whole file exists to prevent.
  kept.push(block.replace(url, name).trim());
}

for (const [name, url] of files) {
  const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(join(OUT, name), bytes);
  console.log(`${name.padEnd(44)} ${(bytes.length / 1024).toFixed(1)} KB`);
}

const header = `/* Generated by scripts/fetch-fonts.mjs — do not edit.
   Be Vietnam Pro and Source Serif 4, SIL Open Font License 1.1.
   Only the latin, latin-ext and vietnamese subsets are vendored. */\n\n`;
writeFileSync(join(OUT, 'fonts.css'), header + kept.join('\n\n') + '\n');

console.log(`\n${files.size} files -> ${OUT}/fonts.css`);
