const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Signs release builds with your own upload key rather than Android's public debug key.
 *
 * Expo's template wires the `release` build type to `signingConfigs.debug` — the stock
 * `androiddebugkey` / `android` credentials, identical on every machine on earth. That is fine for
 * sideloading and rejected by Play, and it proves nothing about who built the binary. Worse, the
 * debug keystore is regenerated by `prebuild --clean`, so two APKs built a week apart carry
 * different signatures and Android refuses to install one over the other.
 *
 * The key itself is deliberately not in this repository and never passes through it. Gradle reads
 * four properties from the per-user `~/.gradle/gradle.properties`:
 *
 *   VANTHANG_UPLOAD_STORE_FILE      absolute path to the .jks
 *   VANTHANG_UPLOAD_KEY_ALIAS
 *   VANTHANG_UPLOAD_STORE_PASSWORD
 *   VANTHANG_UPLOAD_KEY_PASSWORD
 *
 * When they are absent — a fresh clone, a CI runner, someone else's machine — the build falls back
 * to the debug key and still produces something installable, rather than failing on a secret the
 * person cannot have. Which key was actually used is checked *after* the build, with
 * `apksigner verify --print-certs` (see the README): `CN=Vạn Thắng` is yours, `CN=Android Debug`
 * is not publishable. Deliberately not printed during the build — any Gradle error that mentions
 * the signing config dumps the whole thing, passwords included, into the log.
 *
 * A plugin rather than an edit to `android/app/build.gradle`, because that file is regenerated by
 * every prebuild.
 */
const SIGNING_CONFIG = `
    // Injected by plugins/withUploadSigning.js — see that file for why.
    signingConfigs {
        upload {
            if (project.hasProperty('VANTHANG_UPLOAD_STORE_FILE')) {
                storeFile file(VANTHANG_UPLOAD_STORE_FILE)
                storePassword VANTHANG_UPLOAD_STORE_PASSWORD
                keyAlias VANTHANG_UPLOAD_KEY_ALIAS
                keyPassword VANTHANG_UPLOAD_KEY_PASSWORD
            }
        }
    }
`;

module.exports = function withUploadSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    if (contents.includes('VANTHANG_UPLOAD_STORE_FILE')) {
      return cfg;
    }

    // The extra signingConfigs block merges with the template's own; AGP takes the union.
    contents = contents.replace(/^android \{$/m, `android {${SIGNING_CONFIG}`);

    /**
     * Point the release build type at the upload key when it exists.
     *
     * The template's line is `signingConfig signingConfigs.debug` inside `release { … }`, and it
     * also appears inside `debug { … }` — so this replaces only the occurrence that follows the
     * `release {` marker, never both.
     */
    contents = contents.replace(
      /(release \{[\s\S]*?)signingConfig signingConfigs\.debug/,
      `$1signingConfig project.hasProperty('VANTHANG_UPLOAD_STORE_FILE') ? signingConfigs.upload : signingConfigs.debug`,
    );

    cfg.modResults.contents = contents;
    return cfg;
  });
};
