const { withAppBuildGradle } = require('expo/config-plugins');
const { resolve } = require('node:path');

/**
 * Moves the native build staging directory off the repository path, on Windows only.
 *
 * React Native's codegen writes paths like
 *
 *   android/app/.cxx/RelWithDebInfo/<hash>/arm64-v8a
 *     /ReactNativeStaticServerSpec_autolinked_build/CMakeFiles
 *     /react_codegen_ReactNativeStaticServerSpec.dir/react/renderer/components/ReactNativeStaticServerSpec
 *
 * — the module's spec name three times over. Rooted at this repository that measures 265
 * characters, and Windows' classic path limit is 260. `ninja` then fails with
 * `mkdir(...): No such file or directory`, which reads like a missing folder rather than a name
 * five characters too long.
 *
 * `LongPathsEnabled` is already 1 on this machine and does not help: the ninja bundled with
 * Android SDK cmake 3.22.1 predates the manifest opt-in that the flag requires.
 *
 * So the fix is to shorten the root rather than the name — but *inside* the repository, not at
 * `C:/`: nothing this project builds should land on a path the project does not own. The
 * repository root's `.ncxx/` drops `apps/mobile/android/app/.cxx` (30 characters) for `.ncxx`
 * (5), which is enough to bring 265 under the limit with room to spare. It is gitignored, and it
 * disappears with the repository rather than outliving it in a stray folder on C:.
 *
 * A plugin rather than an edit to `android/app/build.gradle`, because that file is regenerated by
 * every `prebuild --clean` — which `scripts/gradle.mjs` runs on every build.
 *
 * Not applied off Windows: macOS and Linux have no such limit, and CI should build at its own
 * natural path.
 */
module.exports = function withShortNativeBuildPath(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (process.platform !== 'win32') {
      return cfg;
    }
    if (cfg.modResults.contents.includes('buildStagingDirectory')) {
      return cfg;
    }

    // The repository root — two levels up from apps/mobile, which is `projectRoot` here.
    const repoRoot = resolve(cfg.modRequest.projectRoot, '..', '..').replace(/\\/g, '/');
    const staging = `${repoRoot}/.ncxx`;

    cfg.modResults.contents = cfg.modResults.contents.replace(
      /^android \{$/m,
      [
        'android {',
        '    // Injected by plugins/withShortNativeBuildPath.js — see that file for why.',
        '    externalNativeBuild {',
        '        cmake {',
        `            buildStagingDirectory = file("${staging}")`,
        '        }',
        '    }',
      ].join('\n'),
    );

    return cfg;
  });
};
