const { withAppBuildGradle } = require('expo/config-plugins');
const { parse } = require('node:path');

/**
 * Moves the native build staging directory off the repository path, on Windows only.
 *
 * React Native's codegen writes paths like
 *
 *   android/app/.cxx/RelWithDebInfo/<hash>/arm64-v8a
 *     /ReactNativeStaticServerSpec_autolinked_build/CMakeFiles
 *     /react_codegen_ReactNativeStaticServerSpec.dir/react/renderer/components/ReactNativeStaticServerSpec
 *
 * — the module's spec name three times over. Rooted at this repository that measures 265
 * characters, and Windows' classic path limit is 260. `ninja` then fails with
 * `mkdir(...): No such file or directory`, which reads like a missing folder rather than a name
 * five characters too long.
 *
 * `LongPathsEnabled` is already 1 on this machine and does not help: the ninja bundled with
 * Android SDK cmake 3.22.1 predates the manifest opt-in that the flag requires.
 *
 * So the fix is to shorten the root rather than the name. `C:/ncxx` in place of the 56 characters
 * of `C:/Users/.../grand-rts-game/apps/mobile` buys back more than enough.
 *
 * A plugin rather than an edit to `android/app/build.gradle`, because that file is regenerated by
 * every `prebuild --clean` — which `scripts/gradle.mjs` runs on every build.
 *
 * Not applied off Windows: macOS and Linux have no such limit, and CI should build at its own
 * natural path.
 */
module.exports = function withShortNativeBuildPath(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (process.platform !== 'win32') {
      return cfg;
    }
    if (cfg.modResults.contents.includes('buildStagingDirectory')) {
      return cfg;
    }

    // The project's own drive, so the staging directory is never on a volume that is not there.
    const drive = parse(cfg.modRequest.projectRoot).root.replace(/\\/g, '/');
    const staging = `${drive}ncxx/van-thang`;

    cfg.modResults.contents = cfg.modResults.contents.replace(
      /^android \{$/m,
      [
        'android {',
        '    // Injected by plugins/withShortNativeBuildPath.js — see that file for why.',
        '    externalNativeBuild {',
        '        cmake {',
        `            buildStagingDirectory = file("${staging}")`,
        '        }',
        '    }',
      ].join('\n'),
    );

    return cfg;
  });
};
