import { readFileSync } from 'node:fs';
export const OUT = 'output/hero-dongho-v2';
export const PUBLIC = 'public/faces-dongho-v2';
const original = JSON.parse(readFileSync('src/ui/faces/parts.generated.ts', 'utf8').split('export const FACE_PART_DEFS: readonly FacePartDef[] = ')[1].split(' as const;')[0]);
const keys = original.map(d => d.key);
export const wardrobe = keys.filter(k => /^(robe|collar|hat|guard|sash|belt|buttons|yem|kesa|badge|hairpin|hair-comb|hair-flower|hair-ribbon|hair-cord|earring)/.test(k));
export const ensembles = ['collar-giaolinh', 'collar-giaolinh-wide', 'collar-twoflap', 'collar-vienlinh', 'collar-doikham', 'collar-tuthan', 'collar-baba', 'collar-nguthan', 'collar-nguthan-tall', 'collar-yem-wrap', 'collar-nhatbinh', 'kesa', 'kesa-red', 'kesa-grey'];
export const definitions = original.map(d => ensembles.includes(d.key)
  ? { ...d, cx: 0, cy: 61, w: 104, h: 68, layer: 35 }
  : /^robe-(body|broad|slim|sloped|square|armour)/.test(d.key)
    ? { ...d, cx: 0, cy: 61, h: 68 }
    : d.key === 'hat-non-quaithao'
      ? { ...d, cx: 0, cy: -14, w: 108, h: 104 }
      : d.key === 'hat-helm-cheeks'
        ? { ...d, cx: 0, cy: -43, w: 76, h: 49 }
        : d.key === 'hat-moqua-tied'
          ? { ...d, cx: 4, cy: -34, w: 78, h: 44 }
    : d.key === 'hat-dinhtu'
      ? { ...d, cx: 5, cy: -54, w: 70, h: 46 }
      : d.key === 'hat-dinhtu-streamers'
        ? { ...d, cx: 0, cy: -49, w: 76, h: 56 }
    : /^hat-band(?:-|$)/.test(d.key)
      ? { ...d, cx: 8, cy: -32, w: 74, h: 38 }
      : d.key === 'hat-helm-dinh' || d.key === 'hat-helm-horned'
        ? { ...d, cx: 0, cy: -52, w: 68, h: 36 }
        : /^sash-/.test(d.key)
          ? { ...d, cx: 0, cy: 84, w: 76, h: 32 }
          : d);
const used = new Set();
const jobs = [];
function group(name, ids, instructions, perSheet = 20) {
  for (let i = 0; i < ids.length; i += perSheet) {
    const partIds = ids.slice(i, i + perSheet);
    partIds.forEach(k => { if (used.has(k)) throw new Error(`Duplicate ${k}`); used.add(k); });
    jobs.push({ name: name + (ids.length > perSheet ? `-${i / perSheet + 1}` : ''), ids: partIds, cols: 4, rows: Math.ceil(partIds.length / 4), instructions });
  }
}
const pick = re => wardrobe.filter(k => re.test(k) && !used.has(k));
const bust = 'Front-facing headless BUST garment only, cropped horizontally at lower chest. Gently sloping shoulders from neck to upper arms, generous hanging cloth, NOT a dome or pill silhouette. A SMALL centered open neck socket at top: no skin, head, neck, hands, mannequin or hair. Every bust same frontal orientation and chest crop. Opaque near-white main cloth with grey flat fold shapes so the game can tint it. Warm-black expressive carved outline and meaningful curved fold strokes, not shiny shading. Collar must actually surround the neck socket. Visible placket or overlap continues naturally down the chest. Never draw a head or skin inside the garment.';
group('bodies', pick(/^robe-(body|broad|slim|sloped|square|armour)/), `${bust} First five are plain loose woven-cloth robe bases: standard, broad shoulders, slender, sloping shoulders, squarer shoulders; simple neck socket, subtle shoulder seams, hanging sleeve folds. Remaining six are restrained medieval Vietnamese armour interpretations: cloth-bound small overlapping plates, vertical laced lamellae, curved fish-scale plates, subdued studded fabric, stitched dark leather panels, then overlapping scalloped plates. Design armour construction with repeated plates/laces and binding; do NOT merely draw wavy lines on a shirt. No horns, fantasy shoulder beasts, European armour, modern tactical armour or Chinese film costume. All tintable armour surfaces near-white/light grey too; strong black details survive dark game tint. Complete neck-facing included.`);
group('ensembles', ensembles, `${bust} In reading order: 1 giao lĩnh narrow crossing lapels closing to WEARER RIGHT/viewer LEFT; 2 broader giao lĩnh lapels same closure; 3 plain practical overlapping wrap same closure; 4 viên lĩnh ROUND neck robe, narrow round facing, continuous plain chest; 5 đối khâm two open parallel front panels with modest plain inner cloth visible; 6 tứ thân open outer panels over yếm, small tied front ends low on chest (late northern form); 7 bà ba simple low neck and center button placket (late southern form); 8 ngũ thân short STANDING collar and fastening curving toward WEARER RIGHT/viewer LEFT, never center front; 9 same ngũ thân a little taller collar; 10 plain outer wrap over modest yếm; 11 Nguyễn Nhật Bình, broad rectangular neck facing extending vertically either side of front opening, restrained floral roundels on facings, no generic V collar; 12 Buddhist ochre kesa draped asymmetrically over plain under-robe with constructed patch seams; 13 brick-red kesa; 14 grey kesa. First eleven near-white tintable cloth, sparing warm-black/grey only; last three fixed ochre, red-brown, grey as specified. Beautiful whole sewn garments, quiet disciplined pattern on Nhật Bình facings only. Do not add jewellery, sashes, waist belts, shoulder armour or rank badges.`);
group('cloth-details', pick(/^robe-|^collar-|^yem|^kesa/), 'Only detached cloth COMPONENTS following the arrangement in image 1, with soft folded seams and convincing facing construction instead of rigid geometric bars. The old drawing is an alignment guide, NOT a quality/style target. Keep corresponding aspect ratio and disconnected holes. Do not add whole torsos or people. All originally white pieces remain near-white with warm-black lines for runtime tint. Thin trim remains thin; yếm is a small neck-tied chest panel, not a diamond jewel; separate upper ties and folded top edge. Crossed lapel strips have soft sewn facing edges. Brocade uses only a restrained repeated geometric border. Oxblood facing, ochre trim, cream/indigo/jade yếm keep fixed earthy colors. Do not draw text, glitter, studs or giant jewels.');
group('fasteners', pick(/^sash|^belt|^buttons/), 'Detached sewn sashes, textile cords, belts and fastening sets. Follow image 1 component placement and aspect ratio. Render material honestly: folded overlapping silk edges with small natural knot, cord with simple double twist, modest inset rectangular jade/ochre plaque belt, knotted cord belt. Buttons sets must remain exactly five small separated fasteners in the original vertical placement, no garment behind. Sashes are fabric, not rectangular bars, necklaces or buckled modern belts. Respect original number and placement of disconnected pieces; do not add people or clothing. Fixed ochre, red-brown, ivory, charcoal and muted jade pigment. Attractive restrained handwork, sparse print strokes.');
group('insignia', pick(/^guard|^badge/), 'Separate shoulder-guard pairs followed by small embroidered square chest badges, matching guide placement and proportions. Guards: layered bound plate shoulder pieces; ochre edge-binding pair; conservative stylised guardian-mask shoulder pair based on Vietnamese guardian-sculpture tradition, not spiked fantasy monster heads. This last compatibility piece is not authenticated battlefield equipment. Badges in reading order crane, pheasant, peacock, dragon (compatibility only), tiger, lion, bear, rhinoceros. A single stylised creature INSIDE a modest square stitched textile border with sparse cloud/ground symbols. Ivory/ochre figure on indigo or red-brown textile. Flat Đông Hồ folk-print creature language, strong silhouettes readable at tiny size. No text, heraldic European shields, flags, enormous gemstones or 3D metal.');
group('jewellery', pick(/^hairpin|^hair-comb|^hair-flower|^hair-ribbon|^hair-cord|^earring/), 'Separate hairpins, comb, small flower, ribbon, hair cord and earring PAIRS in exact guide arrangement. Earrings remain two disconnected pieces with a large EMPTY center (never put a face between them). Preserve each nape pin direction. Materials: modest dark wood comb with real teeth, slender ochre-metal or subdued jade pin, small bead or plain rounded pin head, soft folded cloth ribbon, tiny loop earrings. Restrained late Vietnamese decorative interpretation, not an assertion all dates used all jewellery. No imperial phoenix tiaras, giant floating jewels, tassel forests, modern glamour or extra ornaments. Draw thoughtfully crafted tiny pieces in flat ivory, ochre, jade, cinnabar and black ink.');
group('wraps', pick(/^hat-(khan|khandong|moqua|vanhday)/), 'Vietnamese cloth headwear only, frontal view, no head/face/ears/hair or skin. Replace the crude guide with believable textile construction and gently uneven folded edges. Distinguish wound open-crown khăn vấn (broad overlapping bands around open crown), the compact layered khăn đóng / khăn xếp, the closed square headcloth khăn vuông, the northern mỏ quạ black kerchief with its distinctive small downward POINT at the center forehead and draped side wings, and the large coiled khăn vành dây. Gold/jewel-named compatibility variants are still CLOTH wraps with only a very small restrained ochre stitch or jade fastener, no tiara. Existing proportions are approximate attachment envelopes, not silhouettes to trace. Broad charcoal or deep indigo pigment, selective cream fold lines, brown only where named. No exposed bright white interior slabs. No Sikh turban, headscarf from another region, Chinese opera headwear, Qing hat or queue.');
group('caps', pick(/^hat-(dinhtu|phocdau|xungthien|osa|binhdinh|tamson|duongcan|muni)/), 'Separate Vietnamese-use historic headwear interpretations, frontal only. Đinh Tự: dark raised front, curved cloth cap, restrained folded rear; streamers variant includes two purple-blue rear cloth tails. Phốc Đầu: well-built two-tier black gauze cap, narrow defined headband, two structured HORIZONTAL wings; short, medium and long according to name, never pill-shaped sticks. Xung thiên compatibility: two small rising rear wings, black cloth body, no jewels. Ô sa: compact black gauze cap, crown seams and cloth binding, no modern top hat. Bình đính: flat top, four joined sides, narrower above/wider below (Vietnamese textual evidence), leather/cloth surface. Tam sơn: modest three-lobed black cloth cap; Dương cân: low folded scholar cloth cap; mũ ni: plain close hood, no religious symbols. These latter ambiguous IDs are conservative interpretations, not Chinese source substitutions. Deep indigo/charcoal with few ochre or cream seam strokes, no metal shine, faces, ears, hair or flamboyant ornament.');
group('helmets', pick(/^hat-helm/), 'Nine isolated frontal protective caps/helmets, no people or hair. Restrained Vietnamese medieval reconstruction, exact battlefield forms uncertain. Build a convincing protective bowl with bound lower rim, visible joined panels or overlapping lamellae, sparse rivet/lace marks and modest side/nape protection. Shape follows a head, not a semicircle plus sticks. Names order: plain metal bowl; bowl with SHORT red cloth crest; horned compatibility ID redrawn WITHOUT fantasy horns as a plain four-panel leather cap; laced lamellar cap; Đâu Mâu protective bowl with short top finial; low sewn leather protective cap; bowl with paired cheek pieces and large empty face opening; bowl with small soft red crest; Đinh compatibility ID replace film fantasy helmet with FLAT TOP four-sided joined leather cap narrower above than below. Muted iron-grey, indigo, earth brown, ochre binding, warm-black contour, flat pigment. No Viking horns, samurai kabuto, generic Three Kingdoms warlord helmet, Qing helmet, enormous plume, monsters, spikes or gloss. Preserve main headband attachment width from guide.');
group('hats-bands', pick(/^hat-/), 'Isolated Vietnamese hats and cloth bands. In order named by component list. Nón: natural palm/bamboo conical profile with believable concentric ribs and folded rim, variants steeper cone, compact lacquered soldier nón, broad low northern quai-thao hat with paired cloth straps and EMPTY FACE SPACE, broad flat ba-tầm disc with low raised rim, humble worker nón. Charcoal/ochre/cream, no shiny metallic cone. Coronet/crown compatibility IDs MUST be redesigned as modest coiled cloth court headwraps with small restrained floral/ochre trim, NOT fantasy crowns; they remain withheld from historical rendering. Veil is a plain folded closed cloth kerchief. Bands MUST have visible overlapping soft textile folds, a small knot at the side, and naturally tapered falling tails; never rigid round-ended bars, giant bows, or flat ribbons pasted onto a cap. band=brick red, band-cloth=earth brown, band-warrior=deep indigo with small cinnabar tie, band-gold=ochre woven cloth only. Fur compatibility is a simple dark soft cap with subtly broken edge, no Mongolian or Qing profile. No heads, skin, hair, eyes, lettering or ornaments unsupported by the description.');
if (used.size !== wardrobe.length) throw new Error(`Coverage ${used.size}/${wardrobe.length}: ${wardrobe.filter(k => !used.has(k))}`);
const style = 'Vietnamese Đông Hồ woodblock illustration: decisive warm-black hand-carved contour, expressive tapered fold strokes, broad flat opaque natural pigment, graceful lively silhouette. Match the confident linework and restrained palette of the style reference. High quality craft, not a vector icon, primitive geometry, plastic cartoon, photorealism or cinematic fantasy. No gradients, glow, cast shadow, 3D shading, noisy grunge, paper rectangle, letters or labels.';
export const JOBS = jobs.map(s => ({ ...s, reference: `${OUT}/references/${s.name}.png`, master: `${OUT}/masters/${s.name}.png`, prompt: `Use case: historical-scene. Asset type: modular Vietnamese hero wardrobe PNG sprite sheet. Image 1 is an approximate alignment guide of the components to replace, NOT a historical source and NOT a silhouette to trace. Image 2 is ONLY the project's Đông Hồ drawing-style reference. ${style} ${s.instructions} Exactly ${s.ids.length} components, ONE per cell, in ${s.cols} columns and ${s.rows} equally sized rows in reading order, unused cells empty. All parts centered, generous empty gutters, minimum 24px margin per cell. Draw every requested item separately; do not merge rows or add people. Entire background and holes must be solid pure saturated MAGENTA #ff00ff production matte, no checkerboard, no paper. High resolution sheet, aspect ratio ${s.cols * 320}:${s.rows * 240}. Component order: ${s.ids.join(', ')}.` }));
JOBS.push(JSON.parse(readFileSync('docs/hero-dongho-v2-fit-refinement.json', 'utf8')));
